#!/bin/bash

if [ ! -f aarch64.v ]; then
  echo Run build from the coq directory
  exit 1
fi

if [ -v BBV_DIR ]; then
  BBV_OPT=-Q "$BBV_DIR"
fi

set -ex
make -C lib
coqc $BBV_OPT -Q lib Sail aarch64_extras.v
coqc $BBV_OPT -Q lib Sail aarch64_types.v
coqc -time $BBV_OPT -Q lib Sail aarch64.v
