#!/bin/bash

if [ ! -f aarch64.v ]; then
  echo Run build from the coq directory
  exit 1
fi

if [ ! -d bbv ]; then
  echo 'Check out a copy of https://github.com/mit-plv/bbv and build it.'
  exit 1
fi

set -ex
make -C lib
coqc -R bbv/theories bbv -R lib Sail aarch64_extras.v
coqc -R bbv/theories bbv -R lib Sail aarch64_types.v
coqc -time -R bbv/theories bbv -R lib Sail aarch64.v
